'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AlertTriangle, Info, Scale, Building2, Lock } from 'lucide-react';

export default function DisclaimerModal() {
    const [isOpen, setIsOpen] = useState(false);

    useEffect(() => {
        const handleOpen = () => setIsOpen(true);
        window.addEventListener('open-disclaimer', handleOpen);

        const hasAccepted = localStorage.getItem('ch_assistant_disclaimer_accepted');
        if (!hasAccepted) {
            const timer = setTimeout(() => setIsOpen(true), 1500);
            return () => {
                clearTimeout(timer);
                window.removeEventListener('open-disclaimer', handleOpen);
            };
        }

        return () => window.removeEventListener('open-disclaimer', handleOpen);
    }, []);

    const handleAccept = () => {
        localStorage.setItem('ch_assistant_disclaimer_accepted', 'true');
        setIsOpen(false);
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95, y: 20 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95, y: 20 }}
                        className="w-full max-w-2xl bg-white border-4 border-[#0b0c0c] shadow-2xl relative flex flex-col max-h-[95vh] overflow-hidden"
                    >
                        {/* GOV.UK styled header strip */}
                        <div className="bg-[#f47738] text-white px-6 py-4 flex gap-3 items-center border-b-4 border-[#0b0c0c] flex-shrink-0">
                            <AlertTriangle className="w-8 h-8 flex-shrink-0" />
                            <h2 className="text-2xl font-bold m-0 tracking-tight">Important</h2>
                        </div>

                        <div className="p-6 md:p-8 text-[#0b0c0c] space-y-6 overflow-y-auto flex-grow">
                            <p className="text-lg leading-relaxed font-bold">
                                Before using the Company Assistant, please read and acknowledge the following terms of use.
                            </p>

                            <div className="space-y-4">
                                <div className="flex gap-4 items-start">
                                    <div className="bg-[#f3f2f1] p-3 border border-[#b1b4b6] mt-1">
                                        <Building2 className="w-6 h-6 text-[#1d70b8]" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-xl mb-1">1. Not Affiliated with Companies House</h3>
                                        <p className="text-[#505a5f] leading-relaxed">
                                            This tool is a third-party application developed independently. It is <strong>not affiliated with, endorsed by, or representative of the UK Government, Companies House, or any official body.</strong>
                                        </p>
                                    </div>
                                </div>

                                <div className="flex gap-4 items-start">
                                    <div className="bg-[#f3f2f1] p-3 border border-[#b1b4b6] mt-1">
                                        <Scale className="w-6 h-6 text-[#1d70b8]" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-xl mb-1">2. No Legal Advice Provided</h3>
                                        <p className="text-[#505a5f] leading-relaxed">
                                            The content generated by this tool is for general informational purposes only. It <strong>does not constitute legal advice, official guidance, or professional counsel.</strong> Always seek advice from a qualified legal professional for your specific circumstances.
                                        </p>
                                    </div>
                                </div>

                                <div className="flex gap-4 items-start">
                                    <div className="bg-[#f3f2f1] p-3 border border-[#b1b4b6] mt-1">
                                        <Info className="w-6 h-6 text-[#1d70b8]" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-xl mb-1">3. AI Limitations & Accuracy</h3>
                                        <p className="text-[#505a5f] leading-relaxed">
                                            This assistant uses Artificial Intelligence to process public information. <strong>AI can make mistakes, hallucinate facts, or provide outdated information.</strong> You must independently verify any critical deadlines, fees, or requirements on the official gov.uk website. Reliance on this tool is solely at your own risk.
                                        </p>
                                    </div>
                                </div>

                                <div className="flex gap-4 items-start">
                                    <div className="bg-[#f3f2f1] p-3 border border-[#b1b4b6] mt-1">
                                        <Lock className="w-6 h-6 text-[#1d70b8]" />
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-xl mb-1">4. Privacy & Data Security</h3>
                                        <p className="text-[#505a5f] leading-relaxed">
                                            Please <strong>never share sensitive personal or corporate information</strong> (such as passwords, authentication codes, or detailed financial data) in this chat. Data may be processed by third-party AI providers.
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div className="pt-6 border-t-[3px] border-[#1d70b8] flex flex-col sm:flex-row gap-4 justify-end flex-shrink-0 mt-4">
                                <button
                                    onClick={handleAccept}
                                    className="px-8 py-3 bg-[#00703c] hover:bg-[#005a30] active:top-[2px] relative text-white font-bold text-[19px] border-b-[3px] border-[#002d18] flex items-center justify-center gap-2 shadow-[0_2px_0_#002d18] active:shadow-none transition-none"
                                >
                                    I understand and agree
                                </button>
                            </div>
                        </div>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
}
